/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.app.hidder;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiRootActivity;
import org.appcelerator.kroll.common.Log;

import android.app.Activity;

@Kroll.module(name="TiAppHidder", id="ti.app.hidder")
public class TiAppHidderModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "TiAppHidderModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public TiAppHidderModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public void sendAppToBackground() {
		
	    TiRootActivity app = org.appcelerator.titanium.TiApplication.getInstance().getRootActivity();
	    app.getActivityProxy().getActivity().moveTaskToBack(false);
	    
	}
	
}

